spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/mockbatch?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always
file:
  input: mock_data/books.csv
